
/*  ... include the header file with the prototypes which is
        automatically generated by RTI CAN Blockset */
#include <rtican_usercoding.h>

void AccelCommandEncode(UInt32 *const CAN_Msg, can_tp1_canMsg* const msg) {
    static UInt32 counter = 0;
	CAN_Msg[0] |= counter; 
	if (msg->processed == CAN_TP1_PROCESSED) {	
		counter = (counter + 1)%4;
	}
	
	UInt32 sum = CAN_Msg[0] + CAN_Msg[1] + CAN_Msg[2] + CAN_Msg[3] + CAN_Msg[4] + CAN_Msg[5] + CAN_Msg[6];
	
	CAN_Msg[7] = (UInt8)(0xFFFFFFFF  - sum) + 1; 
}