proj = simulinkproject;
addpath(strcat(proj.RootFolder, '/src/platform'),...
        strcat(proj.RootFolder, '/src/adapter'),...
        strcat(proj.RootFolder, '/src/adapter/models'),...
        strcat(proj.RootFolder, '/src/adapter/c_src'),...
        strcat(proj.RootFolder, '/src/data_files'),...
        strcat(proj.RootFolder, '/src/utilities'),...
        strcat(proj.RootFolder, '/src/test'),...
        strcat(proj.RootFolder, '/src/project'),...
        strcat(proj.RootFolder, '/src'));
        
Simulink.fileGenControl('set',...
                  'CacheFolder', strcat(proj.RootFolder, '/cache'), ...
                  'CodeGenFolder', strcat(proj.RootFolder, '/bld'), ...
                  'createDir', true);