/* Generated by S-function Builder */
#ifndef _PARSEBSM_BUS_H_
#define _PARSEBSM_BUS_H_
/* Read only - STARTS */
#include "tmwtypes.h"




#ifndef _DEFINED_TYPEDEF_FOR_BasicSafetyMessage_
#define _DEFINED_TYPEDEF_FOR_BasicSafetyMessage_ 
typedef struct {
  uint8_T caccFlags_bitmask;
  real32_T setSpeed_m_s;
  real32_T throtPos_percent;
  real32_T lclPN_mm;
  real32_T lclPE_mm;
  real32_T lclPD_mm;
  real32_T roll_deg;
  real32_T pitch_deg;
  real32_T yaw_deg;
  real32_T hPosAcry_m;
  real32_T vPosAcry_m;
  real32_T frwdVel_m_s;
  real32_T rightVel_m_s;
  real32_T downVel_m_s;
  real32_T velAcc_m_s;
  int16_T frwdAcc_mm_s_s;
  int16_T rightAcc_mm_s_s;
  int16_T dwnAcc_mm_s_s;
  uint8_T grpID;
  uint8_T grpSize;
  uint8_T grpMode;
  uint8_T grpManDes;
  uint8_T grpManID;
  uint8_T vehID;
  uint8_T frntCutIn;
  uint8_T vehGrpPos;
  uint8_T vehFltMode;
  uint8_T vehManDes;
  uint8_T vehManID;
  uint8_T distToPVeh_m;
  real32_T relSpdPVeh_m_s;
  uint8_T distToLVeh_m;
  real32_T relSpdLVeh_m_s;
  real32_T desTGapPVeh_s;
  real32_T desTGapLVeh_s;
  uint8_T estDisPVeh_m;
  uint8_T estDisLVeh_m;
  uint8_T desSpeed_m_s;
  uint16_T desTrq_N_m;
  uint8_T msgID;
  uint8_T msgCnt;
  uint32_T id;
  uint16_T secMark_ms;
  real32_T lat_deg;
  real32_T lon_deg;
  real32_T elev_m;
  real32_T semi_major_accuracy_m;
  real32_T semi_minor_accuracy_m;
  real32_T semi_major_accuracy_orientation_deg;
  real32_T speed_m_s;
  uint8_T transmission_enum;
  real32_T heading_deg;
  real32_T angle_deg;
  real32_T vertical_acceleration_g;
  real32_T lat_acceleration_m_s_s;
  real32_T long_acceleration_m_s_s;
  real32_T yaw_rate_deg_s;
  uint8_T wheelBrakes_bitmask;
  boolean_T wheelBrakesUnavailable;
  uint8_T tractionControlState_enum;
  uint8_T anti_lock_brake_status_enum;
  uint8_T stability_control_status_enum;
  uint8_T brake_boost_enum;
  uint8_T auxiliary_brakes_status_enum;
  uint32_T vehicle_height_cm;
  uint32_T vehicle_width_cm;
  uint8_T userDE1;
  uint8_T userDE2;
  uint8_T userDE3;
  uint8_T userDE4;
  uint8_T userDE5;
} BasicSafetyMessage;
#endif

/* Read only - ENDS */


#endif
